/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {},
    colors: {
      transparent: "transparent",
      main: "#E06F2B",
      secondary: '#ffffff',
      light: '#fafafa',
      darkSecondary: '#2a2a2a',
      darkLight: '#353535',
      white: "#333333",
      white: "#fafafa",
      black: "#000000",
      gray: "#C1C5CD",
      red: " #e74c3c ",
      green: "#00ff00",
      blue: "#0000ff",
      yellow: "#ffff00",
      orange: "#ffa500",
      pink: "#ffc0cb",
      lavender: "#e6e6fa",
      teal: "#008080",
      navy: "#000080",
      gold: "#ffd700",
      magenta: "#33333",
      darkMagenta: "#fafafa",
      brown: "#a52a2a",
    },
  },
  plugins: [],
};
